name: build
on: [push, pull_request]
jobs:
  ros2:
    runs-on: ubuntu-20.04
    container:
      image: docker://ros:foxy-ros-base-focal
    steps:
    - name: non-ros-deps
      run: |
        sudo apt update
        sudo apt install -y wget
        # sudo sh -c 'echo "deb http://packages.osrfoundation.org/gazebo/ubuntu-stable `lsb_release -cs` main" > /etc/apt/sources.list.d/gazebo-stable.list'
        # wget https://packages.osrfoundation.org/gazebo.key -O - | apt-key add -       
        sudo apt update && sudo apt install python3-yaml python3-requests \
    - name: create-ws
      run: |
        mkdir -p rmf_demos_ws/src
    - name: checkout # This will check out the current rmf_demos branch for build tests
      uses: actions/checkout@v2
      with:
        path: rmf_demos_ws/src/demonstrations/rmf_demos/
    # - name: ros-deps
    #   run: |
    #     cd rmf_demos_ws
    #     rosdep update
    #     rosdep install --from-paths src --ignore-src --rosdistro foxy -yr
    - name: build
      shell: bash
      run: |
        cd rmf_demos_ws
        source /opt/ros/foxy/setup.bash
        colcon build --packages-select rmf_test_ci
    - name: integration-test
      shell: bash
      run: |
        cd rmf_demos_ws
        source install/setup.bash
        ./install/rmf_test_ci/bin/test_script
